### ISSUE TITLE
Agrupamento dos Clusters

### ISSUE THREAD

**Issue by gabrieldouurado** [proepidesenvolvimento/guardioes-api#108]
Melhorar o agrupamento dos Clusters de modo que sejam apresentados de tamanhos diferentes de acordo com o numero de relatos que ele agreda.

Critério de Aceitação:
- [x] Clusters com um numero maior de relatos agregados

**Comment by RenatoBrittoAraujo** [comment]
Por várias questões muito específicas do funcionamento interno na própria biblioteca do mapa atual, a adição de um texto em clusters informando quantos pinos são agregados por tal cluster resulta em uma redução dramática de performance.

A adição de tal feature requer uma redesign completo do sistema atual de mapa, necessitando montar um mapa dentro de uma webview e sendo renderizado usando HTML e JavaScript web.
