### ISSUE TITLE
Preparar modelo de documento de instuição escolar

### ISSUE THREAD

**Issue by ViniciusPuerto** [proepidesenvolvimento/guardioes-api#120]
Descrição

O modelo de documento de instituição escolar deve ser uma planilha `.xls` que deve seguir padrões para que o cadastro seja feito de forma automática, logo devemos disponibilizar um template para que sejam cadastrados seus departamentos.

Tarefas

- [ ] Criar um teplate de documento;
- [ ] Fazer o upload do documento num serviço de cloud;
- [ ] Disponibilizar o link para dowload;

**Comment by RenatoBrittoAraujo** [comment]
O modelo de tabela pode ser encontrado [aqui](https://gofile.io/d/vBlQbF).

Esta tabela foi definida por @RenatoBrittoAraujo e @gabrieldouurado e validada pela equipe de saúde.
