### ISSUE TITLE
Filtragem dos dashboard por Instituição

### ISSUE THREAD

**Issue by gabrieldouurado** [proepidesenvolvimento/guardioes-api#127]
Realizar a filtragem das visualizações de acordo com a instituição.

Critérios de Aceitação:
- [ ] Wireframe com as informações da instituição

**Comment by RenatoBrittoAraujo** [comment]
Essa issue foi recriada com mais espicificidade [aqui](https://github.com/proepidesenvolvimento/guardioes-web/issues/58)

**Comment by RenatoBrittoAraujo** [comment]
Aguardando teste em ambiente de homologação...

**Comment by RenatoBrittoAraujo** [comment]
Teste em ambiente de homologação foi um sucesso, issue terminada.
