### ISSUE TITLE
Testar rotas e funções para o painel de gerenciamento.

### ISSUE THREAD

**Issue by RenatoBrittoAraujo** [proepidesenvolvimento/guardioes-api#131]
Testar rotas para criar, excluir e editar dados da API a partir de managers e admins.

## Critérios de aceitação:

- [x] Mapear na issue para cada rota QUEM deve ter permissão para usa-las
- [x] CRUD para gerentes - admin
- [x] CRUD para apps - apenas proepi admin god
- [x] CRUD para sintomas - gerente autorizado
- [x] CRUD para sindromes - gerente autorizado
- [x] CRUD para conteúdos - admin
- [x] CRUD para usuários - gerente autorizado

**Comment by alvesitalo** [comment]
• Survey
      See all Surveys: User retornando todas as surveys
• Users
	Get User: Admin god e comum recebendo wrong scope
	Edit User: Admin god e comum recebendo wrong scope
• Contents
See All Contents: Admin recebendo wrong scope, quando deveria poder visualizar.

**Comment by alvesitalo** [comment]
Os endpoints da API no Postman foram atualizados.
