### ISSUE TITLE
Criar rotina para deploy em ambiente de homologação

### ISSUE THREAD

**Issue by ViniciusPuerto** [proepidesenvolvimento/guardioes-api#137]
# Descrição

Precisamos de um forma de subir um ambiente de staging para testarmos as features da API

## Tarefas 

- [x] Entrar em contato com o responsável pela infra no Lappis para sabermos como será feito o deply
- [x] Subir de fato a API no servidor 

## Critérios 

- [x] API deployada

**Comment by RenatoBrittoAraujo** [comment]
@gabrieldouurado entrou em contato e estabeleceu a infra do serviço.
@RenatoBrittoAraujo colocou todos os servidores em produção em ambiente de homologação.
