### ISSUE TITLE
Cadastrar IFB já como Group Manager

### ISSUE THREAD

**Issue by ViniciusPuerto** [proepidesenvolvimento/guardioes-api#138]
# Descrição

Devido à iniciativa de termos mais insituições de ensino e grupos participando do App entrou-se em contato com o IFB para inserirmos eles na nossa base

## Tarefas 

- [ ] Pegar dados necessários para o cadastro do IFB
- [ ] Receber a planilha preenchida com os sub grupos
- [ ] Fazer upload da planilha na API

## Critérios 

- [ ] IFB e seus sub-grupos cadastrados

**Comment by RenatoBrittoAraujo** [comment]
Antes de poder começar essa issue, precisamos das instituições da IFB no formato formulado pela equipe em um arquivo excel .xls

**Comment by RenatoBrittoAraujo** [comment]
Recebemos lista, fazendo upload...

**Comment by RenatoBrittoAraujo** [comment]
IFB está em produção!
