### ISSUE TITLE
Exportação de dados customizados para ES

### ISSUE THREAD

**Issue by gabrieldouurado** [proepidesenvolvimento/guardioes-api#150]
Criar uma rota que exporte os dados por instituição e que alimente o banco de dados do ES dessa forma

Critérios de Aceitação:
- [x] Exportar Users e Surveys de acordo com a instituição
- [x] Testar e garantir segurança e funcionamento da API dada as novas mudanças

**Comment by RenatoBrittoAraujo** [comment]
A solução encontrada envolve um hack. Eu tive que ler o código fonte do searchkick, a gem que utilizamos para comunicação com o elasticsearch, e descobri que ela não é flexível o suficiente para permitir nomes de indices dinâmicos no runtime da instância de um objeto (como o User ou Survey), por isso tive que fazer uma gambiarra que envia duas solicitações ao elasticsearch ao invés de apenas uma. Os dados não são duplicados, mas o envio de duas solicitações é o preço que se paga para fazer o que queremos sem extrair o código fonte da biblioteca.

**Comment by RenatoBrittoAraujo** [comment]
Depois de muito aprendizado do funcionamento interno do ruby, foi possível fazer uma solução que muda um função da biblioteca Searchkick no modulo RecordData, que permite puxar o nome do indice diretamente da instância a ser enviada para o elastic. Dessa forma, o hack antigo foi removido e essa solução fica bem mais simples e a possibilidade de bugs foi reduzida.

**Comment by RenatoBrittoAraujo** [comment]
Aguardando teste em ambiente de homologação...

**Comment by RenatoBrittoAraujo** [comment]
Ainda aguardando teste em ambiente de homologação...

**Comment by RenatoBrittoAraujo** [comment]
Teste em ambiente de homologação foi um sucesso, issue terminada.
