### ISSUE TITLE
Implementação da Vigilancia Ativa

### ISSUE THREAD

**Issue by gabrieldouurado** [proepidesenvolvimento/guardioes-api#157]
**Descrição**<br>
Criar uma lógica que encaminha um email para equipe de vigilância casa um usuário se enquadre na definição de caso da COVID-19.

Informações Presentes no email.

 - Sintomas reportados.
- Id do usuário.
- Id do familiar e grau de parentesco (caso seja um relato de um familiar)

**Critérios de aceite**
- [x] Encaminhar a mensagem para o email da vigilância.

**Comment by gabrieldouurado** [comment]
Adicionar uma pergunta ao usuário se ele quer fazer parte da vigilancia ativa. Caso ele aceite, ele precisará colocar o número de telefone.

Adicionar na tabela de usuário um campo boleano para verificação se o usuário faz parte da vigilancia ativa, adicionar um campo de telefone.

Pedir para Lisiane o texto explicando o que é e como funcionara a vigilancia ativa no GDS. O texto e a será usado na página de aceite da vigilancia ativa.

**Comment by tsrrodrigues** [comment]
Enviar a notificação da vigilancia ativa para um email que a instituição irá fornecer. 

Critérios de Aceitação:

- [ ] Criar o campo para o email no cadastro da instituição.
- [ ] Enviar a notificação para o email cadastrado
