### ISSUE TITLE
CRUD de vacina

### ISSUE THREAD

**Issue by gabrieldouurado** [ProEpiDesenvolvimento/guardioes-api#261]
**Descrição **<br>
É necessário a criação de um CRUD para retornar as vacinas para o aplicativo. 

Os campos necessários seguem abaixo: 
Vacinas:
Nome: Coronavc
Laboratório: Sinovac 
Local que iniciou a produção: China
Laboratório brasileiro que validou a pesquisa: Instituto Butantan 
Número de doses: 2
Intervalo entre as doses: mínimo 14 e ideal 28 dias

Nome: Covishield
Laboratório: Astra-Zeneca
Local que iniciou a produção: Oxsford
Laboratório brasileiro que validou a pesquisa: Instituto Fiocruz
Número de doses: 2
Intervalo entre as doses: 12 semanas

OBS: as vacinas precisam possuir um APP_ID
**Critérios de aceite**
- [ ] Retornar as vacinas disponíveis quando a rota for chamada;

**Comment by jps12** [comment]
Para a modelagem dessa tabela pensei na seguinte solução: 
table_name: vaccines
- name:string
- laboratory:string
- country_origin:string
- brazilian_lab_validator:string
- doses:integer
- max_dose_interval:integer(contado em dias)
- min_dose_interval:integer(contado em dias)

Com relação à níveis de acesso acho que apenas o admin deve ter acesso completo às vacinas (editar, criar e destruir).

**Comment by jps12** [comment]
Foi decidido após conversar com o pessoal da vigilância dos guardiões que o campo *brazilian_lab_validator* é desnecessário. 
Portanto esse campo será retirado da implementação
