### ISSUE TITLE
CRUD de GroupManagerTeam

### ISSUE THREAD

**Issue by jps12** [proepidesenvolvimento/guardioes-api#298]
**Descrição **
Criação do CRUD de GroupManagerTeam e disponibilização das rotas. Deverá ter nome, email, APP_ID, senha, GroupManager_ID. 

**Critérios de aceite**
- [x] CRUD com as respectivas rotas.

**Comment by gabrieldouurado** [comment]
@alvesitalo 

Autenticar todas as rotas -> Somente o GroupManager pode fazer mudanças em um GroupManagerTeam.  
Ao realizar o cadastramento, pegar o group_manager_id por meio do token.  
No show, aparecer somente os GroupManagerTeam daquele usuário.

**Comment by alvesitalo** [comment]
@gabrieldouurado, corrigido!
