### ISSUE TITLE
Verificar permissões para GroupManagerTeams

### ISSUE THREAD

**Issue by alvesitalo** [ProEpiDesenvolvimento/guardioes-api#318]
Ao criar um GroupManagerTeam algumas permissões como para Groups e Dashboards não são aplicadas. É necessário verificar essas permissões nas models e no ability.rb

**Comment by jps12** [comment]
Bem vou comentar aqui na issue porque os bugs podem ser nos dois cantos. 
OBS: GMT = groupManagerTeams e GM = groupManager

1 - Poderia configurar para quando um GMT não tiver acesso a determinada area do painel, essa area não aparecesse para ele. Atualmente o GMT clica na area e recebe uma mensagem de erro

![Screenshot from 2021-08-03 11-38-19](https://user-images.githubusercontent.com/50410689/128037279-31d40467-9e15-484a-b426-a0c44208de78.png)

2 - Independente se a pessoa tem ou não acesso a parte de instituções aparece uma mensagem de falha de autenticação em um alerta. Após isso acontece tudo normalmente.

![Screenshot from 2021-08-03 11-38-07](https://user-images.githubusercontent.com/50410689/128037272-da3693eb-0391-48d5-8802-7380bc7fff2f.png)

3 - Quando o GMT não tem permissão para gerenciar os grupos ele ainda pode ver a lista de grupos e visualizar cada um individualmente. Dá erro apenas quando ele tenta editar alguma coisa. 

PRs envolvidos: [WEB](https://github.com/proepidesenvolvimento/guardioes-web/pull/302) e [API](https://github.com/proepidesenvolvimento/guardioes-api/pull/322)

**Comment by alvesitalo** [comment]
@jps12 
1 - Esse ponto é algo realmente bom, mas tem que ser implementado para todos os usuários também. A forma que os menus laterais foram criados no começo dificulta bastante isso e traria mais trabalho do que essa issue permite. É necessário abrir uma issue sobre isso como melhoria e votar a pontuação dela.

2 - Essa "Falha na autenticação" vem da autenticação do GoData, pra carregar as locations de que cada grupo possui. Então você precisa configurar os dados do seu GM certinho. Como esse alerta também não explica muita coisa vou mudar essa mensagem.

3 - Os GMT podem ver todos os Grupos como conversamos no Telegram.

Já adicionei as correções que falei aqui em cima.
