### ISSUE TITLE
Realizar backup das informações presentes no ES

### ISSUE THREAD

**Issue by jps12** [ProEpiDesenvolvimento/guardioes-api#330]
**Descrição**<br>
Deverá ser criado um backup das informações contidas no Elastic-Search no servidor de produção. 

**Critérios de aceite**
- [x] Os dados salvos de maneira segura e organizada.

**Comment by alvesitalo** [comment]
@jps12 O backup foi realizado no servidor e baixado para a minha máquina também. 
![Captura de Tela 2021-10-01 às 12.46.53.png](https://images.zenhubusercontent.com/5e70191410bdde744f919c18/878e7b33-67db-43dd-8bf7-1911ff607b81)
