### ISSUE TITLE
Criação das estratégias de teste v1.0

### ISSUE THREAD

**Issue by alvesitalo** [ProEpiDesenvolvimento/guardioes-api#354]
Criar **estratégias de teste de software** do projeto Guardiões. E realizar **estudo de CI/CD**.

**Critérios de aceite**
- [x] Definir níveis de teste;
- [x] Definir tipos de teste;
- [x] Definir técnicas de teste;
- [x] Definir o escopo de aplicação de cada estratégia de teste;
- [x] Realizar estudos para utilização de CI/CD (repo guardioes-docs), no Guardiões ;

<hr />
Issue foi realizado no link a seguir: <a href="https://eduardomdr.notion.site/Testes-0230fbc3591d4563988a1054c559a875">Aqui</a> (exceto pelo que está comentado com o 2️⃣.0️⃣)

**Comment by EduardoMdR** [comment]
Issue foi realizado no link a seguir: <a href="https://eduardomdr.notion.site/Testes-0230fbc3591d4563988a1054c559a875">Aqui</a> (exceto pelo que está comentado com o 2️⃣.0️⃣)
