### ISSUE TITLE
Criação das estratégias de teste v2.0

### ISSUE THREAD

**Issue by alvesitalo** [ProEpiDesenvolvimento/guardioes-api#358]
**Descrição:**
Dentre as técnicas na primeira parte
- [x] definir escopo de acordo com as estratégias para back-end
- [x] escopo para front-end
- [x] Criar estratégias de teste de software do projeto Guardiões. E realizar estudo de CI/CD.
- [x] Achar ou montar um tutorial de como implementar CI/CD.

<hr />
Issue foi realizado no link a seguir: <a href="https://eduardomdr.notion.site/Testes-0230fbc3591d4563988a1054c559a875">Aqui</a> e está comentada com 2️⃣.0️⃣

**Comment by EduardoMdR** [comment]
Issue foi realizado no link a seguir: <a href="https://eduardomdr.notion.site/Testes-0230fbc3591d4563988a1054c559a875">Aqui</a> e está comentada com 2️⃣.0️⃣
