### ISSUE TITLE
Atualizar documentação da REST API

### ISSUE THREAD

**Issue by alvesitalo** [ProEpiDesenvolvimento/guardioes-api#362]
**Descrição (Como [quem], eu quero [o quê] para [por quê]?)**<br>
Como Desenvolvedor, preciso ter acesso as rotas atualizadas da API para poder trabalhar nas demandas do Guardiões. Essas rotas estão reunidas em uma collection do Postman.

**Critérios de aceite**
- [x] Rotas atualizadas na collection;
- [x] Sem dados sensíveis a mostra nas requisições do tipo post/put/patch (utilizar dados fictícios);
- [ ] Distribuir e manter documentação apenas entre a equipe presente.<br>

**Comment by alvesitalo** [comment]
Documentação da REST API atualizada e enviada no Time de Desenvolvimento

**Comment by EduardoMdR** [comment]
Documentação testada e aparentemente está tudo certo
