### ISSUE TITLE
Diminuir tempo de resposta das queries de dashboard

### ISSUE THREAD

**Issue by RenatoBrittoAraujo** [proepidesenvolvimento/guardioes-api#50]
**Descrição**<br>

Como USUARIO, preciso de um acesso mais rápido ao dashboard. 
Como PO, preciso diminuir os custos dos servidores.

**Hipóteses**

A priori, um dos possíveis gargalos para a alta latência de resposta parece ser a query que retorna os pinos no mapa. Outras possibilidades também não estão descartadas. Por isso, o primeiro passo dessa issue é testar e documentar testes de hipóteses à respeito desses gargalos.

**Possíveis soluções** 

***Soluções que independem da fonte do problema:***  

- [x] Tornar as queries para a base de dados assíncrona, sendo feitas simultaneamente, os custos de tempo de I/O diminuem.

***Caso o gargalo se confirme sendo o mapa:***  

- [x] Diminuir o número de hits de surveys para as ultimas N da base de dados ou por tempo. (N pode ser 500, por exemplo)
- [x] Implementar um cache que se atualiza a cada N horas/minutos, as queries retornariam o resultado do cache. (N pode ser uma hora)
- [ ] Retornar apenas os casos com sintomas, e talvez alguns sem sintomas para completar.

**Critérios de aceitação**
- [x] Testar e documentar nessa issue hipóteses à respeito dos gargalos.
- [x] Implementar uma ou mais das soluções anteriores de forma a diminuir o tempo de resposta e consumo de processamento para níveis adequados.

**Comment by RenatoBrittoAraujo** [comment]
O @ViniciusPuerto removeu em produção as queries de mapa para testar o efeito, não houve grande necessidade de medir o resultado disso pois ficou claro que o mapa é o maior responsável pelo gargalo.

**Comment by ViniciusPuerto** [comment]
Uma sugestão que também discutimos, tendo em vista o motivo do gargalo, é a criação de um endpoint que renderize o json por horas ou um numero fixo de surveys. Ainda estamos consultando os profissionais da saúde para vermos a melhor forma.
