### ISSUE TITLE
BUG Edição de usuário

### ISSUE THREAD

**Issue by emanuks** [proepidesenvolvimento/guardioes-api#55]
**Descrição**<br>
Ao enviar uma requisição de PATCH para a /users/{userID} retorna status 404.

**Passo a Passo**<br>
Passo a passo para se reproduzir o bug:

1. Enviar uma requisição PATCH para /users/{userID}.
2. O usuário não é editado e a requisição retorna status 404.

**Comportamento Esperado**<br>
As informações do usuário devem ser alteradas e a requisição deve retornar status 200.

**Comment by ViniciusPuerto** [comment]
Uma sugestão pode ser mudar o método de update para dentro do registration controller e sobrescrever o método de update do devise.
[Uma forma de fazer](https://github.com/heartcombo/devise/wiki/How-To:-Allow-users-to-edit-their-account-without-providing-a-password)
