### ISSUE TITLE
Teste gradual das models

### ISSUE THREAD

**Issue by ViniciusPuerto** [proepidesenvolvimento/guardioes-api#61]
**Descrição**<br>
Para melhorar a nossa cobertura de testes vamos testar gradualmente o código já escrito na aplicação a começar pelas Models.
Devem ser testadas todas as models assim como seus relacionamentos e métodos

- Critérios de aceite
- [ ] Model de Admin;
- [ ] Model de App;
- [ ] Model de Content;
- [x] Model de Group;
- [ ] Model de Household;
- [ ] Model de Manager;
- [ ] Model de School Unit;
- [ ] Model de Survey;
- [ ] Model de Symptom;
- [x] Model de User;
- [x] Model TwitterAPI
- [x] Model ManagerGroupPermission

**Comment by RenatoBrittoAraujo** [comment]
Foram criado ambiente de testes de um sistema de CI com travis. Os testes de models feitos foram para Users, ManagerGroupPermissions, Groups e TwitterAPI.
