### ISSUE TITLE
Método delete de syndromes e symptoms não está funcionando

### ISSUE THREAD

**Issue by tsrrodrigues** [proepidesenvolvimento/guardioes-api#96]
**Descrição**<br>
Método delete de syndromes e symptoms não estpa funcionando.<br>

**Erro**<br>
"status": 500,
  "error": "Internal Server Error",
  "exception": "#<ActiveRecord::InvalidForeignKey: PG::ForeignKeyViolation: ERROR:  update or delete on table \"symptoms\" violates foreign key constraint \"fk_rails_68e0a23081\" on table \"syndrome_symptom_percentages\"\nDETAIL:  Key (id)=(12) is still referenced from table \"syndrome_symptom_percentages\".\n: DELETE FROM \"symptoms\" WHERE \"symptoms\".\"id\" = $1>",

**Passo a Passo**<br>
Passo a passo para se reproduzir o bug:
1. Crie uma sindrome e um sintoma linkados um com o outro
2. Tente deletar algum
3. Veja o erro

**Comportamento Esperado**<br>
Possível deletar a síndrome ou o sintoma

**Comment by RenatoBrittoAraujo** [comment]
Este problema era causado por não deletar as associações ligadas às sindromes e sintomas (Messages e SyndromeSymptomPercentage). Desde o ultimo PR está consertado.
