### ISSUE TITLE
Retorno das Síndromes está incorreto para os Reports

### ISSUE THREAD

**Issue by tsrrodrigues** [proepidesenvolvimento/guardioes-api#98]
**Descrição**<br>
Ao realizar um report com sintomas, está retornando no objeto top_3(síndromes) síndromes que não estão relacionadas a nenhum dos sintomas reportados. Por exemplo, como está apenas criado no servidor a Sindrome Gripal. Ao realizar um report com o sintoma "Dor de Cabeça", que não está dentre os sintomas dessa síndrome, é retornado dentro das top_3 a Síndrome Gripal.

**Passo a Passo**<br>
Passo a passo para se reproduzir o bug:
1. Faça um report com um sintoma que não está relacionado à Síndrome Gripal
2. Receba como resposta no objeto message.top_3 a Síndrome Gripal

**Comportamento Esperado**<br>
Retornar apenas síndromes em que os sintomas batam com os sintomas reportados.

**Comment by RenatoBrittoAraujo** [comment]
Este problema na verdade foi um design mal pensado da API, que retornava dados irrelevantes. O último PR conserta esse problema.
